# Generated by Django 5.2.4 on 2025-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_otp_code_userprofile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user_disputed',
            field=models.BooleanField(default=False),
        ),
    ]
